#!/usr/bin/env bash
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
if [[ "$OSTYPE" == "msys" ]]; then
	py -3 -u "$SCRIPTPATH"/scripts/pmbuild.py "$@"
else
	python3 -u "$SCRIPTPATH"/scripts/pmbuild.py "$@"
fi